apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api-deployment
  labels:
    app: employee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
      - name: employee-api
        image: localhost:9003/employee:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: IfNotPresent
---
